# Generated by Django 4.2.3 on 2023-07-18 12:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0002_house'),
    ]

    operations = [
        migrations.AddField(
            model_name='house',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='rent_management.housetype'),
            preserve_default=False,
        ),
    ]
