# Generated by Django 4.2.3 on 2023-07-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0003_house_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='', max_length=50)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
