# Generated by Django 4.2.3 on 2023-07-20 08:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0005_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenants',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.IntegerField(default=1)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_management.user')),
                ('rented_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_management.house')),
            ],
        ),
    ]
