# Generated by Django 4.2.3 on 2023-07-20 09:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0006_tenants'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_no', models.CharField(default='', max_length=20)),
                ('paid_amount', models.IntegerField(default=0)),
                ('paid_date', models.DateTimeField(auto_now_add=True)),
                ('outstanding', models.IntegerField(default=0)),
                ('tenants_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rent_management.tenants')),
            ],
        ),
    ]
