# Generated by Django 4.2.3 on 2023-07-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0007_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_id',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='aadhaar_number',
            field=models.CharField(default='', max_length=50),
        ),
    ]
