# Generated by Django 4.2.3 on 2023-07-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent_management', '0008_user_email_id_alter_user_aadhaar_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='outstanding',
        ),
        migrations.AlterField(
            model_name='user',
            name='mobile_number',
            field=models.CharField(default='Not Given', max_length=13, null=True),
        ),
    ]
